@startuml
skinparam classAttributeIconSize 0

!include media/uml-class-journalpost.iuml
!include media/uml-datatype-elektronisksignatur.iuml
!include media/uml-class-dokumentbeskrivelse.iuml
!include media/uml-class-dokumentobjekt.iuml

Arkivstruktur.ElektroniskSignatur -[hidden]-> Sakarkiv.Journalpost
Arkivstruktur.ElektroniskSignatur --[hidden]-> Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Dokumentobjekt <-[hidden]- Arkivstruktur.ElektroniskSignatur
Arkivstruktur.Dokumentbeskrivelse "+dokumentbeskrivelse 1" o-> "+dokumentobjekt 0..*" Arkivstruktur.Dokumentobjekt
@enduml
