@startuml
class Arkivstruktur.Merknad {
  +systemID : SystemID [0..1]
  +merknadstekst : string
  +merknadstype : Merknadstype [0..1]
  +merknadsdato : datetime
  +merknadRegistrertAv : string [0..1]
  +referanseMerknadRegistrertAv : SystemID [0..1]
}
@enduml
