@startuml
class Arkivstruktur.Dokumentobjekt {
  +systemID : SystemID [0..1]
  +versjonsnummer : integer
  +variantformat : Variantformat
  +format : Format [0..1]
  +formatDetaljer : string [0..1]
  +opprettetDato : datetime [0..1]
  +opprettetAv : string [0..1]
  +referanseDokumentfil : string [0..1]
  +filnavn : string [0..1]
  +sjekksum : string [0..1]
  +mimeType : string [0..1]
  +sjekksumAlgoritme : string [0..1]
  +filstoerrelse : string [0..1]
  +elektroniskSignatur : ElektroniskSignatur [0..1]
}
@enduml
