@startuml
skinparam classAttributeIconSize 0
'FIXME dropped caption "class Fig02_Stereotyper"

!include media/uml-datatype-gradering.iuml
!include media/uml-codelist-graderingskode.iuml

Arkivstruktur.Gradering -[hidden]-> Kodelister.Graderingskode
@enduml
