@startuml
skinparam nodesep 100
class LoggingOgSporing.Hendelseslogg <Endringslogg> {
  +hendelsetype : Hendelsetype
  +beskrivelse : string [0..1]
  +hendelseDato : datetime
}
LoggingOgSporing.Endringslogg <|-- LoggingOgSporing.Hendelseslogg
@enduml
