@startuml
class Arkivstruktur.Arkivenhet {
  +systemID : SystemID
  +oppdatertDato : datetime [0..1]
  +opprettetDato : datetime [0..1]
  +opprettetAv : string [0..1]
  +oppdatertAv : string [0..1]
  +referanseOppdatertAv : SystemID
  +referanseOpprettetAv : SystemID
}
@enduml
