@startuml
skinparam nodesep 100
hide circle
class Admin.Tilgang {
  +systemID : SystemID [0..1] [1..1]
  +rolle : string
  +tilgangskategori : Tilgangskategori
  +referanseArkivenhet : SystemID [0..1]
  +tilgangsrestriksjon : Tilgangsrestriksjon [0..1]
  +les : boolean
  +ny : boolean
  +endre : boolean
  +slett : boolean
}
@enduml
