@startuml
'FIXME dropped caption "class Fig04_Generalisering"
class Basisregistrering < Registrering >
class Journalpost < Basisregistrering >
class Moeteregistrering < Basisregistrering >
Basisregistrering <|-- Journalpost
Basisregistrering <|-- Moeteregistrering
@enduml
