@startuml
class Arkivstruktur.Mappe <Arkivenhet> {
  +mappeID : string [0..1] [1..1]
  +tittel : string
  +offentligTittel : string [0..1]
  +beskrivelse : string [0..1]
  +noekkelord : string [0..*]
  +dokumentmedium : Dokumentmedium [0..1] [1..1]
  +oppbevaringssted : string [0..*]
  +avsluttetDato : datetime [0..1]
  +avsluttetAv : string [0..1]
  +referanseAvsluttetAv : SystemID [0..1]
  +kassasjon : Kassasjon [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
  +referanseForelderMappe : SystemID [0..1]
  +virksomhetsspesifikkeMetadata : VirksomhetsspesifikkeMetadata [0..1]
}
@enduml
