@startuml
skinparam classAttributeIconSize 0
!include kapitler/media/uml-class-arkivenhet.iuml
!include kapitler/media/uml-class-endringslogg.iuml
!include kapitler/media/uml-class-hendelseslogg.iuml
!include kapitler/media/uml-codelist-hendelsetype.iuml
LoggingOgSporing.Endringslogg <|-- LoggingOgSporing.Hendelseslogg
Arkivstruktur.Arkivenhet "0..1" o- "logg 0..*" LoggingOgSporing.Hendelseslogg
LoggingOgSporing.Hendelseslogg -[hidden]- Kodelister.Hendelsetype
@enduml
