@startuml
skinparam classAttributeIconSize 0
!include kapitler/media/uml-class-klasse.iuml
!include kapitler/media/uml-class-mappe.iuml
!include kapitler/media/uml-class-kryssreferanse.iuml

Arkivstruktur.Registrering "+registrering 0..1" <--> "+kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
Arkivstruktur.Kryssreferanse "+kryssreferanse 0..*" <--> "+mappe 0..1" Arkivstruktur.Mappe
Arkivstruktur.Kryssreferanse "+kryssreferanse 0..*" <--> "+klasse 0..1" Arkivstruktur.Klasse
Arkivstruktur.Klasse o-> "+underklasse o..*" Arkivstruktur.Klasse
Arkivstruktur.Mappe o-> "+undermappe o..*" Arkivstruktur.Mappe
Arkivstruktur.Klasse "+klasse 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
@enduml
