@startuml
class Arkivstruktur.Konvertering {
  +systemID : SystemID [0..1] [1..1]
  +konvertertDato : datetime [0..1] [1..1]
  +konvertertAv : string [0..1] [1..1]
  +konvertertFraFormat : Format [0..1] [1..1]
  +konvertertTilFormat : Format [0..1] [1..1]
  +konverteringsverktoey : string [0..1]
  +konverteringskommentar : string [0..1]
}
@enduml
