@startuml
skinparam nodesep 100
hide circle
class Sakarkiv.Avskrivning {
  +systemID : SystemID [0..1] [1..1]
  +avskrivningsdato : datetime [0..1] [1..1]
  +avskrevetAv : string [0..1] [1..1]
  +referanseAvskrevetAv : SystemID [0..1] [1..1]
  +avskrivningsmaate : Avskrivningsmaate [0..1] [1..1]
  +referanseAvskrivesAvJournalpost : SystemID [0..1]
  +referanseAvskrivesAvKorrespondansepart : SystemID [0..1]
}
class Sakarkiv.Journalpost <Registrering> {
}
Sakarkiv.Journalpost *-- "avskrivning 0..*" Sakarkiv.Avskrivning
@enduml
