@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.Registrering <Arkivenhet> {
  +arkivertDato : datetime [0..1] [1..1]
  +arkivertAv : string [0..1] [1..1]
  +referanseArkivertAv : SystemID [0..1] [1..1]
  +kassasjon : Kassasjon [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
  +referanseArkivdel : SystemID [0..1] [1..1]
  +registreringsID : string [0..1] [1..1]
  +tittel : string
  +offentligTittel : string [0..1]
  +beskrivelse : string [0..1]
  +noekkelord : string [0..*]
  +forfatter : string [0..*]
  +dokumentmedium : Dokumentmedium [0..1] [1..1]
  +oppbevaringssted : string [0..*]
  +virksomhetsspesifikkeMetadata : any [0..1]
}
class Arkivstruktur.Arkivdel <Arkivenhet> {
}
Arkivstruktur.Arkivdel "arkivdel 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
class Arkivstruktur.Arkivenhet {
}
Arkivstruktur.Arkivenhet <|-- Arkivstruktur.Registrering
class Arkivstruktur.Klasse <Arkivenhet> {
}
Arkivstruktur.Klasse "klasse 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
class Arkivstruktur.Mappe <Arkivenhet> {
}
Arkivstruktur.Mappe "mappe 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
class Arkivstruktur.Kryssreferanse <Arkivenhet> {
}
Arkivstruktur.Registrering "registrering 0..1" *--> "kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
class Arkivstruktur.Dokumentbeskrivelse <Arkivenhet> {
}
Arkivstruktur.Registrering "registrering 1..*" o--> "dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
class Arkivstruktur.Korrespondansepart {
}
Arkivstruktur.Registrering *-- "korrespondansepart 0..*" Arkivstruktur.Korrespondansepart
class Arkivstruktur.Merknad {
}
Arkivstruktur.Registrering *-- "merknad 0..*" Arkivstruktur.Merknad
class Arkivstruktur.Part {
}
Arkivstruktur.Registrering *-- "part 0..*" Arkivstruktur.Part
class Arkivstruktur.Gradering <<dataType>> {
}
Arkivstruktur.Registrering *-- Arkivstruktur.Gradering
class Arkivstruktur.Kassasjon <<dataType>> {
}
Arkivstruktur.Registrering *-- Arkivstruktur.Kassasjon
class Arkivstruktur.Skjerming <<dataType>> {
}
Arkivstruktur.Registrering *-- Arkivstruktur.Skjerming
class Sakarkiv.Arkivnotat <Registrering> {
}
Arkivstruktur.Registrering <|-- Sakarkiv.Arkivnotat
class Sakarkiv.Journalpost <Registrering> {
}
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost
class Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator {
}
Arkivstruktur.Registrering o-- "nasjonalidentifikator 0..*" Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator
@enduml
