@startuml
skinparam nodesep 100
hide circle
class Sakarkiv.Arkivnotat <Registrering> {
  +dokumentetsDato : datetime [0..1]
  +mottattDato : datetime [0..1]
  +sendtDato : datetime [0..1]
  +forfallsdato : datetime [0..1]
  +offentlighetsvurdertDato : datetime [0..1]
  +antallVedlegg : integer [0..1]
  +utlaantDato : datetime [0..1]
  +utlaantTil : string [0..1]
  +referanseUtlaantTil : SystemID [0..1]
}
class Sakarkiv.Dokumentflyt {
}
Sakarkiv.Arkivnotat *-- "dokumentflyt 0..*" Sakarkiv.Dokumentflyt
class Arkivstruktur.Registrering <Arkivenhet> {
}
Arkivstruktur.Registrering <|-- Sakarkiv.Arkivnotat
@enduml
