@startuml
class Arkivstruktur.ElektroniskSignatur <<dataType>> {
  +elektroniskSignaturSikkerhetsnivaa : ElektroniskSignaturSikkerhetsnivaa
  +elektroniskSignaturVerifisert : ElektroniskSignaturVerifisert
  +verifisertDato : datetime
  +verifisertAv : string
  +referanseVerifisertAv : SystemID [0..1]
}
@enduml
