@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.KorrespondansepartPerson <Korrespondansepart> {
  +personidentifikator : Personidentifikator [0..*]
  +navn : string
  +postadresse : EnkelAdresse [0..1]
  +bostedsadresse : EnkelAdresse [0..1]
  +kontaktinformasjon : Kontaktinformasjon [0..1]
}
class Arkivstruktur.Korrespondansepart {
}
Arkivstruktur.Korrespondansepart <|-- Arkivstruktur.KorrespondansepartPerson
class Arkivstruktur.EnkelAdresse <<dataType>> {
}
Arkivstruktur.KorrespondansepartPerson *-- Arkivstruktur.EnkelAdresse
class Arkivstruktur.Kontaktinformasjon <<dataType>> {
}
Arkivstruktur.KorrespondansepartPerson *-- Arkivstruktur.Kontaktinformasjon
@enduml
