@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.Korrespondansepart {
  +systemID : SystemID [0..1] [1..1]
  +korrespondanseparttype : Korrespondanseparttype [0..1] [1..1]
  +virksomhetsspesifikkeMetadata : any [0..1]
}
class Arkivstruktur.KorrespondansepartEnhet <Korrespondansepart> {
}
Arkivstruktur.Korrespondansepart <|-- Arkivstruktur.KorrespondansepartEnhet
class Arkivstruktur.KorrespondansepartIntern <Korrespondansepart> {
}
Arkivstruktur.Korrespondansepart <|-- Arkivstruktur.KorrespondansepartIntern
class Arkivstruktur.KorrespondansepartPerson <Korrespondansepart> {
}
Arkivstruktur.Korrespondansepart <|-- Arkivstruktur.KorrespondansepartPerson
class Arkivstruktur.Registrering <Arkivenhet> {
}
Arkivstruktur.Registrering *-- "korrespondansepart 0..*" Arkivstruktur.Korrespondansepart
@enduml
