@startuml
class Arkivstruktur.Skjerming <<dataType>> {
  +tilgangsrestriksjon : Tilgangsrestriksjon
  +skjermingshjemmel : string
  +skjermingMetadata : SkjermingMetadata [0..*]
  +skjermingDokument : SkjermingDokument [0..1]
  +skjermingsvarighet : integer [0..1]
  +skjermingOpphoererDato : date [0..1]
}
@enduml
