@startuml
class Sakarkiv.Saksmappe <Mappe> {
  +saksaar : integer
  +sakssekvensnummer : integer
  +saksdato : date
  +administrativEnhet : string [0..1]
  +referanseAdministrativEnhet : SystemID [0..1]
  +saksansvarlig : string
  +referanseSaksansvarlig : SystemID [0..1]
  +journalenhet : string [0..1]
  +saksstatus : Saksstatus
  +utlaantDato : date [0..1]
  +utlaantTil : string [0..1]
  +referanseUtlaantTil : SystemID [0..1]
}
@enduml
