@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.ElektroniskSignatur <<dataType>> {
  +elektroniskSignaturSikkerhetsnivaa : ElektroniskSignaturSikkerhetsnivaa
  +elektroniskSignaturVerifisert : ElektroniskSignaturVerifisert
  +verifisertDato : datetime
  +verifisertAv : string [0..1] [1..1]
  +referanseVerifisertAv : SystemID [0..1] [1..1]
}
class Arkivstruktur.Dokumentbeskrivelse <Arkivenhet> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.ElektroniskSignatur
class Arkivstruktur.Dokumentobjekt <Arkivenhet> {
}
Arkivstruktur.Dokumentobjekt *-- Arkivstruktur.ElektroniskSignatur
class Sakarkiv.Journalpost <Registrering> {
}
Sakarkiv.Journalpost *-- Arkivstruktur.ElektroniskSignatur
@enduml
