@startuml
skinparam classAttributeIconSize 0
!include kapitler/media/uml-class-arkivskaper.iuml
!include kapitler/media/uml-class-arkiv.iuml
!include kapitler/media/uml-class-arkivdel.iuml
!include kapitler/media/uml-class-klassifikasjonssystem.iuml
!include kapitler/media/uml-class-klasse.iuml
!include kapitler/media/uml-class-kryssreferanse.iuml
!include kapitler/media/uml-class-mappe.iuml
!include kapitler/media/uml-class-merknad.iuml
!include kapitler/media/uml-class-saksmappe.iuml
!include kapitler/media/uml-class-sakspart.iuml
!include kapitler/media/uml-class-journalpost.iuml
!include kapitler/media/uml-class-korrespondansepart.iuml
class MoeteOgUtvalgsbehandling.Moetemappe {
  +moetenummer : string [0..1]
  +utvalg : string
  +moetedato : datetime
  +moetested : string [0..1]
  +referanseForrigeMoete : SystemID [0..1]
  +referanseNesteMoete : SystemID [0..1]
}
!include kapitler/media/uml-class-registrering.iuml
!include kapitler/media/uml-class-dokumentbeskrivelse.iuml
!include kapitler/media/uml-class-basisregistrering.iuml
!include kapitler/media/uml-class-dokumentobjekt.iuml
class MoeteOgUtvalgsbehandling.Moeteregistrering {
  +moeteregistreringstype : Moeteregistreringstype
  +moetesakstype : Moetesakstype
  +moeteregistreringsstatus : Moeteregistreringsstatus [0..1]
  +administrativEnhet : string
  +referanseAdministrativEnhet : SystemID [0..1]
  +saksbehandler : string
  +referanseSaksbehandler : SystemID [0..1]
  +referanseTilMoeteregistrering : SystemID [0..1]
  +referanseFraMoeteregistrering : SystemID [0..1]
}
!include kapitler/media/uml-class-konvertering.iuml
!include kapitler/media/uml-datatype-elektronisksignatur.iuml

Arkivstruktur.Arkivskaper "+arkivskaper 1..*" <-o "+arkiv 0..*" Arkivstruktur.Arkiv
Arkivstruktur.Arkiv o--> "+underarkiv 0..*" Arkivstruktur.Arkiv
Arkivstruktur.Arkiv "+arkiv 1" o--> "+arkivdel 0..*" Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+klassifikasjonssystem 0..*" <-o "+arkivdel 1..*" Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+sekundaerklassifikasjonssystem 0..*" <-o Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+klassifikasjonssystem 0..1" o--> "+klasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Klasse o-> "+underklasse 0..1" Arkivstruktur.Klasse
Arkivstruktur.Klasse "+klasse 0..1" <-> "+kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
Arkivstruktur.Mappe "+mappe 0..1" <-> "+kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
Arkivstruktur.Kryssreferanse "+kryssreferanse 0..*" <--> "+registrering 0..1" Arkivstruktur.Basisregistrering
Arkivstruktur.Arkivdel "+arkivdel 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Klasse "+sekundaerklassifikasjon 0..*" <--o Sakarkiv.Saksmappe
Arkivstruktur.Klasse "+klasse 0..*" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Mappe <|-- Sakarkiv.Saksmappe
Arkivstruktur.Mappe <|- MoeteOgUtvalgsbehandling.Moetemappe
Sakarkiv.Saksmappe *--> "+sakspart 0..*" Sakarkiv.Sakspart
Arkivstruktur.Mappe *-> "+merknad 0..*" Arkivstruktur.Merknad
Arkivstruktur.Mappe "+mappe 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Merknad "+merknad 0..*" <--* Arkivstruktur.Basisregistrering
Arkivstruktur.Registrering <|- Arkivstruktur.Basisregistrering
Arkivstruktur.Registrering "+registrering 1..*" o--> "+dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Merknad "+merknad 0..*" <--* Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Klasse "+klasse 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Dokumentbeskrivelse "+dokumentbeskrivelse 1" o--> "+dokumentobjekt 0..*" Arkivstruktur.Dokumentobjekt
Arkivstruktur.Basisregistrering <|-- Sakarkiv.Journalpost
Arkivstruktur.Basisregistrering <|-- MoeteOgUtvalgsbehandling.Moeteregistrering
Sakarkiv.Journalpost *--> "+korrespondansepart 0..*" Sakarkiv.Korrespondansepart
Arkivstruktur.Dokumentobjekt *--> "+konvertering 0..*" Arkivstruktur.Konvertering
@enduml
