@startuml
class Arkivstruktur.Arkiv <Arkivenhet> {
  +tittel : string
  +beskrivelse : string [0..1]
  +arkivstatus : Arkivstatus [0..1] [1..1]
  +dokumentmedium : Dokumentmedium [0..1] [1..1]
  +oppbevaringssted : string [0..*]
  +avsluttetDato : datetime [0..1]
  +avsluttetAv : string [0..1]
  +referanseAvsluttetAv : SystemID [0..1]
}
@enduml
