@startuml
skinparam nodesep 100
hide circle
class LoggingOgSporing.Endringslogg {
  +systemID : SystemID [0..1] [1..1]
  +referanseArkivenhet : SystemID [0..1]
  +referanseMetadata : string [0..1]
  +endretAv : string [0..1] [1..1]
  +referanseEndretAv : SystemID [0..1] [1..1]
  +tidligereVerdi : string [0..1]
  +nyVerdi : string [0..1]
}
class Arkivstruktur.Arkivenhet {
}
Arkivstruktur.Arkivenhet "0..1" o-- "endringslogg 0..*" LoggingOgSporing.Endringslogg
class LoggingOgSporing.Hendelseslogg {
}
LoggingOgSporing.Hendelseslogg <|-- LoggingOgSporing.Endringslogg
@enduml
