@startuml
skinparam nodesep 100
class Arkivstruktur.Registrering <Arkivenhet> {
  +arkivertDato : datetime [0..1]
  +arkivertAv : string [0..1]
  +referanseArkivertAv : SystemID [0..1]
  +kassasjon : Kassasjon [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
  +referanseArkivdel : SystemID [0..1]
  +registreringsID : string [0..1]
  +tittel : string
  +offentligTittel : string [0..1]
  +beskrivelse : string [0..1]
  +noekkelord : string [0..*]
  +forfatter : string [0..*]
  +dokumentmedium : Dokumentmedium [0..1]
  +oppbevaringssted : string [0..*]
  +virksomhetsspesifikkeMetadata : any [0..1]
}
Arkivstruktur.Arkivdel "arkivdel 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Arkivenhet <|-- Arkivstruktur.Registrering
Arkivstruktur.Klasse "klasse 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Korrespondansepart "korrespondansepart 0..*" *-- Arkivstruktur.Registrering
Arkivstruktur.Mappe "mappe 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Merknad "merknad 0..*" *-- Arkivstruktur.Registrering
Arkivstruktur.Part "part 0..*" *-- Arkivstruktur.Registrering
Arkivstruktur.Registrering "registrering 0..1" *--> "kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
Arkivstruktur.Registrering "registrering 1..*" o--> "dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Registrering <|-- Sakarkiv.Arkivnotat
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost
Arkivstruktur.Registrering o-- "nasjonalidentifikator 0..*" Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator
@enduml
