@startuml
class Arkivstruktur.ElektroniskSignatur <<dataType>> {
  +elektroniskSignaturSikkerhetsnivaa : ElektroniskSignaturSikkerhetsnivaa
  +elektroniskSignaturVerifisert : ElektroniskSignaturVerifisert
  +verifisertDato : datetime
  +verifisertAv : string [0..1] [1..1]
  +referanseVerifisertAv : SystemID [0..1] [1..1]
}
@enduml
