@startuml
class Kodelister.Format <<codelist>> {
  +Ukjent format = av/0
  +Ren tekst = x-fmt/111
  +TIFF versjon 6 = fmt/353
  +PDF/A 1a - ISO 19005-1:2005 = fmt/95
  +PDF/A 1b - ISO 19005-1:2005 = fmt/354
  +XML = fmt/101
  +JPEG = fmt/42
  +SOSI = av/1
  +MPEG-2 = x-fmt/386
  +MP3 = fmt/134
  +PNG = fmt/11
}
@enduml
