@startuml
class LoggingOgSporing.Endringslogg {
  +systemID : SystemID [0..1] [1..1]
  +referanseArkivenhet : SystemID [0..1]
  +referanseMetadata : string [0..1]
  +endretDato : datetime [0..1] [1..1]
  +endretAv : string [0..1] [1..1]
  +referanseEndretAv : SystemID [0..1] [1..1]
  +tidligereVerdi : string [0..1]
  +nyVerdi : string [0..1]
}
@enduml
