@startuml
skinparam classAttributeIconSize 0
skinparam nodesep 180

!include kapitler/media/uml-class-arkivskaper.iuml
!include kapitler/media/uml-class-arkiv.iuml
!include kapitler/media/uml-class-klassifikasjonssystem.iuml
!include kapitler/media/uml-class-klasse.iuml
!include kapitler/media/uml-class-arkivdel.iuml
!include kapitler/media/uml-class-mappe.iuml
!include kapitler/media/uml-class-merknad.iuml
!include kapitler/media/uml-class-registrering.iuml
!include kapitler/media/uml-class-basisregistrering.iuml
!include kapitler/media/uml-class-dokumentbeskrivelse.iuml
!include kapitler/media/uml-class-dokumentobjekt.iuml
!include kapitler/media/uml-class-konvertering.iuml
!include kapitler/media/uml-datatype-elektronisksignatur.iuml

Arkivstruktur.Arkiv "+arkiv 0..*" o--> "+arkivskaper 1..*" Arkivstruktur.Arkivskaper
Arkivstruktur.Arkiv "+overarkiv 0..1" o--> "+underarkiv 0..*" Arkivstruktur.Arkiv
Arkivstruktur.Arkiv "+arkiv 1" o--> "+arkivdel 0..*" Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+klassifikasjonssystem 0..1" <--o "+arkivdel 1..*" Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+sekundaerklassifikasjonssystem 0..*" <--o Arkivstruktur.Arkivdel

Arkivstruktur.Klassifikasjonssystem "+klassifikasjonssystem 0..1" o--> "+klasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Arkivdel "nestearkivdel 0..1" o--> "forrigearkivdel 0..1" Arkivstruktur.Arkivdel
Arkivstruktur.Arkivdel "+arkivdel 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Arkivdel "+arkivdel 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Klasse "+klasse 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Klasse "+klasse 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Klasse "+overklasse 0..1" o--> "+underklasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Mappe "+overmappe 0..1" o--> "+undermappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Mappe "+mappe 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Merknad "+merknad 0..*" <-* Arkivstruktur.Mappe
Arkivstruktur.Merknad "+merknad 0..*" <--* Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Basisregistrering -|> Arkivstruktur.Registrering
Arkivstruktur.Merknad "+merknad 0..*" <--* Arkivstruktur.Basisregistrering
Arkivstruktur.Registrering "+registrering 1..*" o--> "+dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Dokumentbeskrivelse "+dokumentbeskrivelse 1" o--> "+dokumentobjekt 0..*" Arkivstruktur.Dokumentobjekt
Arkivstruktur.Dokumentobjekt *-> "+konvertering 0..*" Arkivstruktur.Konvertering
Arkivstruktur.ElektroniskSignatur -[hidden]-> Arkivstruktur.Dokumentobjekt
@enduml
