@startuml
skinparam nodesep 100
hide circle
class Kodelister.Journalstatus <<codelist>> {
  +Journalført = J
  +Ferdigstilt fra saksbehandler = F
  +Godkjent av leder = G
  +Ekspedert = E
  +Arkivert = A
  +Utgår = U
  +Midlertidig registrering av innkommet dokument = M
  +Saksbehandler har registrert innkommet dokument = S
  +Reservert dokument = R
}
@enduml
