@startuml
skinparam classAttributeIconSize 0

!include kapitler/media/uml-codelist-arkivstatus.iuml
!include kapitler/media/uml-codelist-dokumentmedium.iuml
!include kapitler/media/uml-codelist-klassifikasjonstype.iuml
!include kapitler/media/uml-codelist-merknadstype.iuml
!include kapitler/media/uml-codelist-skjermingdokument.iuml
!include kapitler/media/uml-codelist-arkivdelstatus.iuml
!include kapitler/media/uml-codelist-dokumenttype.iuml
!include kapitler/media/uml-codelist-tilknyttetregistreringsom.iuml
!include kapitler/media/uml-codelist-format.iuml
!include kapitler/media/uml-codelist-dokumentstatus.iuml
!include kapitler/media/uml-codelist-skjermingmetadata.iuml
!include kapitler/media/uml-codelist-flytstatus.iuml
!include kapitler/media/uml-codelist-variantformat.iuml
!include kapitler/media/uml-codelist-saksstatus.iuml
!include kapitler/media/uml-codelist-korrespondanseparttype.iuml
!include kapitler/media/uml-codelist-slettingstype.iuml
!include kapitler/media/uml-codelist-journalposttype.iuml
!include kapitler/media/uml-codelist-presedensstatus.iuml
!include kapitler/media/uml-codelist-avskrivningsmaate.iuml
!include kapitler/media/uml-codelist-journalstatus.iuml
!include kapitler/media/uml-codelist-kassasjonsvedtak.iuml
!include kapitler/media/uml-codelist-graderingskode.iuml
!include kapitler/media/uml-codelist-elektronisksignaturverifisert.iuml
!include kapitler/media/uml-codelist-moetesakstype.iuml
!include kapitler/media/uml-codelist-moeteregistreringstype.iuml
!include kapitler/media/uml-codelist-elektronisksignatursikkerhetsnivaa.iuml
!include kapitler/media/uml-codelist-mappetype.iuml
!include kapitler/media/uml-codelist-tilgangskategori.iuml
!include kapitler/media/uml-codelist-moeteregistreringsstatus.iuml
!include kapitler/media/uml-codelist-moetedeltakerfunksjon.iuml
!include kapitler/media/uml-codelist-partrolle.iuml
!include kapitler/media/uml-codelist-tilgangsrestriksjon.iuml
!include kapitler/media/uml-codelist-land.iuml
!include kapitler/media/uml-codelist-postnummer.iuml
@enduml
