@startuml
skinparam nodesep 100
hide circle
class Sakarkiv.Journalpost <Registrering> {
  +journalaar : integer [0..1] [1..1]
  +journalsekvensnummer : integer [0..1] [1..1]
  +journalpostnummer : integer [0..1] [1..1]
  +journalposttype : Journalposttype [0..1] [1..1]
  +journalstatus : Journalstatus [0..1] [1..1]
  +journaldato : datetime [0..1] [1..1]
  +dokumentetsDato : datetime [0..1] [1..1]
  +mottattDato : datetime [0..1] [1..1]
  +sendtDato : datetime [0..1]
  +forfallsdato : datetime [0..1]
  +offentlighetsvurdertDato : datetime [0..1]
  +antallVedlegg : integer [0..1]
  +utlaantDato : datetime [0..1]
  +utlaantTil : string [0..1]
  +referanseUtlaantTil : SystemID [0..1]
  +journalenhet : string [0..1] [1..1]
  +elektroniskSignatur : ElektroniskSignatur [0..1]
}
class Sakarkiv.Avskrivning {
}
Sakarkiv.Journalpost *-- "avskrivning 0..*" Sakarkiv.Avskrivning
class Sakarkiv.Dokumentflyt {
}
Sakarkiv.Journalpost *-- "dokumentflyt 0..*" Sakarkiv.Dokumentflyt
class Arkivstruktur.ElektroniskSignatur <<dataType>> {
}
Sakarkiv.Journalpost *-- Arkivstruktur.ElektroniskSignatur
class Sakarkiv.Presedens {
}
Sakarkiv.Presedens "presedens 0..*" *--> "journalpost 0..*" Sakarkiv.Journalpost
class Arkivstruktur.Registrering <Arkivenhet> {
}
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost
@enduml
