@startuml

!include kapitler/media/uml-codelist-korrespondanseparttype.iuml
!include kapitler/media/uml-class-korrespondansepart.iuml
!include kapitler/media/uml-class-korrespondansepartintern.iuml
!include kapitler/media/uml-class-korrespondansepartperson.iuml
!include kapitler/media/uml-class-korrespondansepartenhet.iuml

Arkivstruktur.Registrering *- "+korrespondansepart 0..*" Arkivstruktur.Korrespondansepart
Arkivstruktur.Registrering *-- "+part 0..*" Arkivstruktur.Part
Arkivstruktur.Korrespondansepart <-[hidden]- Kodelister.Korrespondanseparttype
Arkivstruktur.Korrespondansepart <|-- Sakarkiv.KorrespondansepartPerson
Arkivstruktur.Korrespondansepart <|-- Sakarkiv.KorrespondansepartEnhet
Arkivstruktur.Korrespondansepart <|-- Sakarkiv.KorrespondansepartIntern

note "ISO liste" as isoliste
note "fra posten.no" as fraposten
class Kodelister.Land <<codelist>>
class Kodelister.Postnummer <<codelist>>
Arkivstruktur.EnkelAdresse <-[hidden]- Kodelister.Land
Kodelister.Land .. isoliste
Arkivstruktur.EnkelAdresse <-[hidden]- Kodelister.Postnummer
Kodelister.Postnummer .. fraposten

!include kapitler/media/uml-class-administrativenhet.iuml
!include kapitler/media/uml-class-bruker.iuml

Arkivstruktur.KorrespondansepartIntern <-[hidden]-- Admin.AdministrativEnhet
Admin.AdministrativEnhet "+enhet 0..*" <--> "+bruker 0..*" Admin.Bruker

!include kapitler/media/uml-datatype-enkeladresse.iuml

Arkivstruktur.KorrespondansepartPerson <-[hidden]-- Arkivstruktur.EnkelAdresse
Arkivstruktur.KorrespondansepartEnhet <-[hidden]-- Arkivstruktur.EnkelAdresse

!include kapitler/media/uml-datatype-kontaktinformasjon.iuml
!include kapitler/media/uml-class-part.iuml
!include kapitler/media/uml-class-partperson.iuml
!include kapitler/media/uml-class-partenhet.iuml

class Sakarkiv.Saksmappe <Mappe>
class Sakarkiv.Journalpost <Registrering>
Arkivstruktur.Mappe <|-- Sakarkiv.Saksmappe
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost

Arkivstruktur.Mappe *-- "+part 0..*" Arkivstruktur.Part
Arkivstruktur.Part <|-- Sakarkiv.PartPerson
Arkivstruktur.Part <|-- Arkivstruktur.PartEnhet
Arkivstruktur.PartPerson <-[hidden]- Arkivstruktur.Kontaktinformasjon
Arkivstruktur.PartEnhet <-[hidden]- Arkivstruktur.Kontaktinformasjon

@enduml
