@startuml
skinparam nodesep 100
class Arkivstruktur.Konvertering {
  +systemID : SystemID [0..1]
  +konvertertDato : datetime
  +konvertertAv : string
  +konvertertFraFormat : Format
  +konvertertTilFormat : Format
  +konverteringsverktoey : string [0..1]
  +konverteringskommentar : string [0..1]
}
Arkivstruktur.Dokumentobjekt o-- "konvertering 0..*" Arkivstruktur.Konvertering
@enduml
