@startuml
skinparam nodesep 100
hide circle
class MoeteOgUtvalgsbehandling.Moeteregistreringstype <<codelist>> {
  +Møteinnkalling = MI
  +Saksframlegg = SF
  +Saksprotokoll = SP
  +Møteprotokoll = MP
  +Saksliste = SL
  +Offentlig saksliste = OL
  +Vedlegg til møtesak = VL
}
class MoeteOgUtvalgsbehandling.Moeteregistrering <Registrering> {
}
MoeteOgUtvalgsbehandling.Moeteregistrering *-- "moeteregistreringstype 0..1" MoeteOgUtvalgsbehandling.Moeteregistreringstype
@enduml
