@startuml
class Arkivstruktur.Gradering <<dataType>> {
  +graderingskode : Graderingskode [0..1] [1..1]
  +graderingsdato : datetime [0..1] [1..1]
  +gradertAv : string [0..1] [1..1]
  +referanseGradertAv : SystemID [0..1] [1..1]
  +nedgraderingsdato : datetime [0..1]
  +nedgradertAv : string [0..1]
  +referanseNedgradertAv : SystemID [0..1]
}
@enduml
