@startuml
class Sakarkiv.Avskrivning {
  +systemID : SystemID [0..1] [1..1]
  +avskrivningsdato : datetime [0..1] [1..1]
  +avskrevetAv : string [0..1] [1..1]
  +referanseAvskrevetAv : SystemID [0..1] [1..1]
  +avskrivningsmaate : Avskrivningsmaate [0..1] [1..1]
  +referanseAvskrivesAvJournalpost : SystemID [0..1]
  +referanseAvskrivesAvKorrespondansepart : SystemID [0..1]
}
@enduml
