@startuml
skinparam nodesep 100
hide circle
class Sakarkiv.Journalpost <Registrering> {
  +journalaar : integer [0..1]
  +journalsekvensnummer : integer [0..1]
  +journalpostnummer : integer
  +journalposttype : Journalposttype
  +journalstatus : Journalstatus
  +journaldato : date
  +dokumentetsDato : date [0..1]
  +mottattDato : datetime [0..1]
  +sendtDato : date [0..1]
  +forfallsdato : date [0..1]
  +offentlighetsvurdertDato : date [0..1]
  +antallVedlegg : integer [0..1]
  +utlaantDato : date [0..1]
  +utlaantTil : string [0..1]
  +referanseUtlaantTil : SystemID [0..1]
  +journalenhet : string [0..1]
  +elektroniskSignatur : ElektroniskSignatur [0..1]
}
class Sakarkiv.Avskrivning {
}
Sakarkiv.Avskrivning "avskrivning 0..*" *-- Sakarkiv.Journalpost
class Sakarkiv.Dokumentflyt {
}
Sakarkiv.Dokumentflyt "dokumentflyt 0..*" *-- Sakarkiv.Journalpost
class Arkivstruktur.ElektroniskSignatur <<dataType>> {
}
Sakarkiv.Journalpost *-- Arkivstruktur.ElektroniskSignatur
class Sakarkiv.Presedens {
}
Sakarkiv.Presedens "presedens 0..*" *--> "journalpost 0..*" Sakarkiv.Journalpost
class Arkivstruktur.Registrering <Arkivenhet> {
}
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost
@enduml
