@startuml
class Arkivstruktur.Arkivenhet {
  +systemID : SystemID [0..1]
  +endretDato : datetime [0..1]
  +opprettetDato : datetime [0..1]
  +opprettetAv : string [0..1]
  +endretAv : string [0..1]
  +referanseEndretAv : SystemID [0..1]
  +referanseOpprettetAv : SystemID [0..1]
}
@enduml
