@startuml
skinparam classAttributeIconSize 0

!include kapitler/media/uml-class-klasse.iuml
!include kapitler/media/uml-class-mappe.iuml
!include kapitler/media/uml-class-dokumentbeskrivelse.iuml
!include kapitler/media/uml-class-registrering.iuml
!include kapitler/media/uml-class-merknad.iuml
!include kapitler/media/uml-datatype-skjerming.iuml
!include kapitler/media/uml-codelist-skjermingmetadata.iuml
!include kapitler/media/uml-codelist-skjermingdokument.iuml
!include kapitler/media/uml-codelist-tilgangsrestriksjon.iuml
!include kapitler/media/uml-class-tilgang.iuml

Arkivstruktur.Klasse o--> "+underklasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Klasse "+klasse 0..1" o-> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Mappe o-> "+undermappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Mappe "+mappe 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Klasse "+klasse 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Registrering "+registrering" o--> "+dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Mappe *-> "+merknad 0..*" Arkivstruktur.Merknad
Arkivstruktur.Dokumentbeskrivelse *-> "+merknad 0..*" Arkivstruktur.Merknad

Arkivstruktur.Registrering <-[hidden]- Arkivstruktur.Skjerming
Arkivstruktur.Dokumentbeskrivelse <-[hidden]- Arkivstruktur.Skjerming
Arkivstruktur.Dokumentbeskrivelse <-[hidden]- Kodelister.Tilgangsrestriksjon
Admin.Tilgang <-[hidden]- Kodelister.Tilgangsrestriksjon
Arkivstruktur.Skjerming <-[hidden]- Kodelister.SkjermingMetadata
Arkivstruktur.Skjerming <-[hidden]- Kodelister.SkjermingDokument

@enduml
