@startuml
skinparam classAttributeIconSize 0

!include kapitler/media/uml-class-saksmappe-all.iuml
!include kapitler/media/uml-class-presedens.iuml
!include kapitler/media/uml-class-sakspart.iuml

class Arkivstruktur.Klasse <Arkivenhet>
Arkivstruktur.Klasse "\n\n+sekundaerklassifikasjon 0..*"  <--o Sakarkiv.Saksmappe
Arkivstruktur.Klasse o--> "\n+underklasse 0..*" Arkivstruktur.Klasse
Sakarkiv.Saksmappe "+sak 0..*" o--> "+presedens 0..*" Sakarkiv.Presedens
Sakarkiv.Saksmappe *--> "+sakspart 0..*" Sakarkiv.Sakspart

@enduml
