@startuml

!include kapitler/media/uml-codelist-korrespondanseparttype.iuml
!include kapitler/media/uml-class-korrespondansepart.iuml
!include kapitler/media/uml-class-korrespondansepartintern.iuml
!include kapitler/media/uml-class-korrespondansepartperson.iuml
!include kapitler/media/uml-class-korrespondansepartenhet.iuml

Arkivstruktur.Registrering *- "+korrespondansepart 0..*" Sakarkiv.Korrespondansepart
Arkivstruktur.Registrering *-- "+part 0..*" Sakarkiv.Part
Sakarkiv.Korrespondansepart <-[hidden]- Kodelister.Korrespondanseparttype
Sakarkiv.Korrespondansepart <|-- Sakarkiv.KorrespondansepartPerson
Sakarkiv.Korrespondansepart <|-- Sakarkiv.KorrespondansepartEnhet
Sakarkiv.Korrespondansepart <|-- Sakarkiv.KorrespondansepartIntern

note "ISO liste" as isoliste
note "fra posten.no" as fraposten
class Kodelister.Land <<codelist>>
class Kodelister.Postnummer <<codelist>>
Sakarkiv.EnkelAdresse <-[hidden]- Kodelister.Land
Kodelister.Land .. isoliste
Sakarkiv.EnkelAdresse <-[hidden]- Kodelister.Postnummer
Kodelister.Postnummer .. fraposten

!include kapitler/media/uml-class-administrativenhet.iuml
!include kapitler/media/uml-class-bruker.iuml

Sakarkiv.KorrespondansepartIntern <-[hidden]-- Admin.AdministrativEnhet
Admin.AdministrativEnhet "+enhet 0..*" <--> "+bruker 0..*" Admin.Bruker

!include kapitler/media/uml-datatype-enkeladresse.iuml

Sakarkiv.KorrespondansepartPerson <-[hidden]-- Sakarkiv.EnkelAdresse
Sakarkiv.KorrespondansepartEnhet <-[hidden]-- Sakarkiv.EnkelAdresse

!include kapitler/media/uml-datatype-kontaktinformasjon.iuml
!include kapitler/media/uml-class-part.iuml
!include kapitler/media/uml-class-partperson.iuml
!include kapitler/media/uml-class-partenhet.iuml

class Sakarkiv.Saksmappe <Mappe>
class Sakarkiv.Journalpost <Registrering>
Arkivstruktur.Mappe <|-- Sakarkiv.Saksmappe
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost

Arkivstruktur.Mappe *-- "+part 0..*" Sakarkiv.Part
Sakarkiv.Part <|-- Sakarkiv.PartPerson
Sakarkiv.Part <|-- Sakarkiv.PartEnhet
Sakarkiv.PartPerson <-[hidden]- Sakarkiv.Kontaktinformasjon
Sakarkiv.PartEnhet <-[hidden]- Sakarkiv.Kontaktinformasjon

@enduml
