@startuml
skinparam classAttributeIconSize 0
'FIXME dropped caption "class Fig01_Klasse"
class Arkivstruktur.Registrering < Arkivenhet > {
  +arkivertDato : datetime [0..1]
  +arkivertAv : string [0..1]
  +referanseArkivertAv : SystemID [0..1]
  +kassasjon : Kassasjon [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
  +referanseArkivdel : SystemID

  __ notes __
  En registrering inneholder bare de metadata som
  er nødvendig dersom dokumentet arkiveres uten
  journalføring.  Dette kalles også forenklet
  registrering
}
@enduml
