@startuml
skinparam nodesep 100
class Sakarkiv.Avskrivning {
  +systemID : SystemID [0..1]
  +avskrivningsdato : date
  +avskrevetAv : string
  +referanseAvskrevetAv : SystemID [0..1]
  +avskrivningsmaate : Avskrivningsmaate
  +referanseAvskrivesAvJournalpost : SystemID [0..1]
  +referanseAvskrivesAvKorrespondansepart : SystemID [0..1]
}
Sakarkiv.Avskrivning "avskrivning 0..*" *-- Sakarkiv.Journalpost
@enduml
