@startuml
skinparam classAttributeIconSize 0
skinparam nodesep 180

!include kapitler/media/uml-class-arkivskaper.iuml
!include kapitler/media/uml-class-arkiv.iuml
!include kapitler/media/uml-class-arkivdel.iuml
!include kapitler/media/uml-class-klassifikasjonssystem.iuml
!include kapitler/media/uml-class-klasse.iuml
!include kapitler/media/uml-class-kryssreferanse.iuml
!include kapitler/media/uml-class-mappe.iuml
!include kapitler/media/uml-class-merknad.iuml
!include kapitler/media/uml-class-saksmappe.iuml
!include kapitler/media/uml-class-part.iuml
!include kapitler/media/uml-class-journalpost.iuml
!include kapitler/media/uml-class-korrespondansepart.iuml
!include kapitler/media/uml-datatype-moetedeltaker.iuml
!include kapitler/media/uml-class-moetemappe.iuml
!include kapitler/media/uml-class-registrering.iuml
!include kapitler/media/uml-class-arkivnotat.iuml
!include kapitler/media/uml-class-dokumentbeskrivelse.iuml
!include kapitler/media/uml-class-dokumentobjekt.iuml
!include kapitler/media/uml-class-moeteregistrering.iuml
!include kapitler/media/uml-class-konvertering.iuml
!include kapitler/media/uml-datatype-elektronisksignatur.iuml

Arkivstruktur.Arkivskaper "+arkivskaper 1..*" <-o "+arkiv 0..*" Arkivstruktur.Arkiv
Arkivstruktur.Arkiv "+overarkiv 0..1" o--> "+underarkiv 0..*" Arkivstruktur.Arkiv
Arkivstruktur.Arkiv "+arkiv 1" o--> "+arkivdel 0..*" Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+klassifikasjonssystem 0..*" <-o "+arkivdel 1..*" Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+sekundaerklassifikasjonssystem 0..*" <-o Arkivstruktur.Arkivdel
Arkivstruktur.Klassifikasjonssystem "+klassifikasjonssystem 0..1" o--> "+klasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Klasse "+overklasse 0..1" o-> "+underklasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Klasse "+klasse 0..1" <-> "+kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
Arkivstruktur.Mappe "+mappe 0..1" <-> "+kryssreferanse 0..*" Arkivstruktur.Kryssreferanse
Arkivstruktur.Kryssreferanse "+kryssreferanse 0..*" <--> "+registrering 0..1" Arkivstruktur.Registrering
Arkivstruktur.Arkivdel "nestearkivdel 0..1" o--> "forrigearkivdel 0..1" Arkivstruktur.Arkivdel
Arkivstruktur.Arkivdel "+arkivdel 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Klasse "+sekundaerklassifikasjon 0..*" <--o Sakarkiv.Saksmappe
Arkivstruktur.Klasse "+klasse 0..*" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Mappe <|-- Sakarkiv.Saksmappe
Arkivstruktur.Mappe <|- MoeteOgUtvalgsbehandling.Moetemappe
MoeteOgUtvalgsbehandling.Moetemappe "forrigemoetemappe 0..1" o-> "nestemoetemappe 0..1" MoeteOgUtvalgsbehandling.Moetemappe
MoeteOgUtvalgsbehandling.Moetemappe --* "moetedeltaker 1..*" MoeteOgUtvalgsbehandling.Moetedeltaker

Arkivstruktur.Mappe *--> "+part 0..*" Arkivstruktur.Part
Arkivstruktur.Mappe *-> "+merknad 0..*" Arkivstruktur.Merknad
Arkivstruktur.Mappe "+mappe 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Merknad "+merknad 0..*" <--* Arkivstruktur.Registrering
Arkivstruktur.Registrering "+registrering 1..*" o--> "+dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Merknad "+merknad 0..*" <--* Arkivstruktur.Dokumentbeskrivelse
Arkivstruktur.Klasse "+klasse 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Dokumentbeskrivelse "+dokumentbeskrivelse 1" o--> "+dokumentobjekt 0..*" Arkivstruktur.Dokumentobjekt
Arkivstruktur.Registrering <|-- Sakarkiv.Arkivnotat
Arkivstruktur.Registrering <|-- Sakarkiv.Journalpost
Arkivstruktur.Registrering <|-- MoeteOgUtvalgsbehandling.Moeteregistrering
Admin.Bruker "referanseSaksbehandler" o- MoeteOgUtvalgsbehandling.Moeteregistrering
Admin.AdministrativEnhet "referanseAdministrativEnhet" o- MoeteOgUtvalgsbehandling.Moeteregistrering
MoeteOgUtvalgsbehandling.Moeteregistrering "framoeteregistrering 0..*" o-> "tilmoeteregistrering 0..*" MoeteOgUtvalgsbehandling.Moeteregistrering

Arkivstruktur.Registrering *--> "+korrespondansepart 0..*" Arkivstruktur.Korrespondansepart
Arkivstruktur.Registrering *--> "+part 0..*" Arkivstruktur.Part
Arkivstruktur.Dokumentbeskrivelse *--> "+part 0..*" Arkivstruktur.Part
Arkivstruktur.Dokumentobjekt *--> "+konvertering 0..*" Arkivstruktur.Konvertering
@enduml
