@startuml
skinparam nodesep 100
hide circle
class Sakarkiv.Dokumentflyt {
  +systemID : SystemID [0..1] [1..1]
  +flytTil : string [0..1] [1..1]
  +referanseFlytTil : SystemID [0..1] [1..1]
  +flytFra : string [0..1] [1..1]
  +referanseFlytFra : SystemID [0..1] [1..1]
  +flytMottattDato : datetime
  +flytSendtDato : datetime [0..1] [1..1]
  +flytStatus : FlytStatus [0..1] [1..1]
  +flytMerknad : string [0..1]
}
class Sakarkiv.Arkivnotat <Registrering> {
}
Sakarkiv.Arkivnotat *-- "dokumentflyt 0..*" Sakarkiv.Dokumentflyt
class Sakarkiv.Journalpost <Registrering> {
}
Sakarkiv.Journalpost *-- "dokumentflyt 0..*" Sakarkiv.Dokumentflyt
@enduml
