@startuml
class LoggingOgSporing.Endringslogg {
  +systemID : SystemID
  +referanseArkivenhet : SystemID
  +referanseMetadata : string [0..1]
  +endretDato : datetime
  +endretAv : string
  +referanseEndretAv : SystemID
  +tidligereVerdi : string [0..1]
  +nyVerdi : string [0..1]
}
@enduml
