@startuml
skinparam nodesep 100
class Arkivstruktur.Arkivdel <Arkivenhet> {
  +tittel : string
  +beskrivelse : string [0..1]
  +arkivdelstatus : Arkivdelstatus
  +dokumentmedium : Dokumentmedium [0..1]
  +oppbevaringssted : string [0..*]
  +avsluttetDato : datetime [0..1]
  +avsluttetAv : string [0..1]
  +referanseAvsluttetAv : SystemID [0..1]
  +arkivperiodeStartDato : date [0..1]
  +arkivperiodeSluttDato : date [0..1]
  +referanseForloeper : SystemID [0..1]
  +referanseArvtaker : SystemID [0..1]
  +kassasjon : Kassasjon [0..1]
  +utfoertKassasjon : UtfoertKassasjon [0..1]
  +sletting : Sletting [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
}
Arkivstruktur.Arkiv "arkiv 1" o--> "arkivdel 0..*" Arkivstruktur.Arkivdel
Arkivstruktur.Arkivdel "arkivdel 0..1" o--> "mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Arkivdel "arkivdel 0..1" o--> "registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Arkivdel "arkivdel 1..*" o--> "klassifikasjonssystem 0..1" Arkivstruktur.Klassifikasjonssystem
Arkivstruktur.Arkivdel "nestearkivdel 0..1" o--> "forrigearkivdel 0..1" Arkivstruktur.Arkivdel
Arkivstruktur.Arkivdel *-- Arkivstruktur.Gradering
Arkivstruktur.Arkivdel *-- Arkivstruktur.Kassasjon
Arkivstruktur.Arkivdel *-- Arkivstruktur.Skjerming
Arkivstruktur.Arkivdel *-- Arkivstruktur.Sletting
Arkivstruktur.Arkivdel *-- Arkivstruktur.UtfoertKassasjon
Arkivstruktur.Arkivdel o-- "sekundaerklassifikasjonssystem 0..*" Arkivstruktur.Klassifikasjonssystem
Arkivstruktur.Arkivenhet <|-- Arkivstruktur.Arkivdel
@enduml
