@startuml
skinparam nodesep 100
hide circle
class Admin.AdministrativEnhet {
  +systemID : SystemID [0..1] [1..1]
  +administrativEnhetNavn : string
  +kortnavn : string [0..1]
  +opprettetDato : datetime [0..1] [1..1]
  +opprettetAv : string [0..1] [1..1]
  +avsluttetDato : datetime [0..1]
  +administrativEnhetsstatus : string
  +referanseOverordnetEnhet : SystemID [0..1]
  +virksomhetsspesifikkeMetadata : VirksomhetsspesifikkeMetadata [0..1]
}
class Admin.Bruker {
}
Admin.AdministrativEnhet "administrativenhet 0..*" *--> "bruker 0..*" Admin.Bruker
class VirksomhetsspesifikkeMetadata.VirksomhetsspesifikkeMetadata <<VirksomhetsspesifikkeMetadata>> {
}
Admin.AdministrativEnhet *-- VirksomhetsspesifikkeMetadata.VirksomhetsspesifikkeMetadata
@enduml
