@startuml
skinparam nodesep 100
hide circle
class Sakarkiv.Dokumentflyt {
  +systemID : SystemID [0..1]
  +flytTil : string
  +referanseFlytTil : SystemID [0..1]
  +flytFra : string
  +referanseFlytFra : SystemID [0..1]
  +flytMottattDato : datetime
  +flytSendtDato : datetime
  +flytStatus : FlytStatus
  +flytMerknad : string [0..1]
}
class Sakarkiv.Arkivnotat <Registrering> {
}
Sakarkiv.Dokumentflyt "dokumentflyt 0..*" *-- Sakarkiv.Arkivnotat
class Sakarkiv.Journalpost <Registrering> {
}
Sakarkiv.Dokumentflyt "dokumentflyt 0..*" *-- Sakarkiv.Journalpost
@enduml
