@startuml
'FIXME dropped caption "class Fig04_Generalisering"
class Registrering < Arkivenhet >
class Journalpost < Registrering >
class Moeteregistrering < Registrering >
Registrering <|-- Journalpost
Registrering <|-- Moeteregistrering
@enduml
