@startuml
class Arkivstruktur.Arkivdel <Arkivenhet> {
  +tittel : string
  +beskrivelse : string [0..1]
  +arkivdelstatus : Arkivdelstatus
  +dokumentmedium : Dokumentmedium [0..1]
  +oppbevaringssted : string [0..*]
  +avsluttetDato : datetime [0..1]
  +avsluttetAv : string [0..1]
  +referanseAvsluttetAv : SystemID [0..1]
  +arkivperiodeStartDato : datetime [0..1]
  +arkivperiodeSluttDato : datetime [0..1]
  +referanseForloeper : SystemID [0..1]
  +referanseArvtaker : SystemID [0..1]
  +kassasjon : Kassasjon [0..1]
  +utfoertKassasjon : UtfoertKassasjon [0..1]
  +sletting : Sletting [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
}
@enduml
