@startuml
skinparam classAttributeIconSize 0
skinparam nodesep 180

class Arkivstruktur.Mappe <Arkivenhet>
class Arkivstruktur.Registrering <Arkivenhet>
!include kapitler/media/uml-class-bygning.iuml
!include kapitler/media/uml-class-enhetsidentifikator.iuml
!include kapitler/media/uml-class-matrikkel.iuml
!include kapitler/media/uml-class-nasjonalidentifikator.iuml
!include kapitler/media/uml-class-personidentifikator.iuml
!include kapitler/media/uml-class-foedselsnummer.iuml
!include kapitler/media/uml-class-dnummer.iuml
!include kapitler/media/uml-class-plan.iuml
!include kapitler/media/uml-class-posisjon.iuml
!include kapitler/media/uml-codelist-koordinatsystem.iuml

Arkivstruktur.Mappe --> "+undermappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Registrering "+registrering 0..*" <-o "+mappe 0..1" Arkivstruktur.Mappe
Arkivstruktur.Mappe *--> "+nasjonalidentifikator 0..*\n\n" Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator
Arkivstruktur.Registrering *--> "+nasjonalidentifikator 0..*\n" Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator
Arkivstruktur.NasjonaleIdentifikatorer.Posisjon -|> Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator
Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator <|- Arkivstruktur.NasjonaleIdentifikatorer.Personidentifikator
Arkivstruktur.NasjonaleIdentifikatorer.Personidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.DNummer
Arkivstruktur.NasjonaleIdentifikatorer.Personidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.Foedselsnummer
Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.Enhetsidentifikator
Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.Bygning
Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.Matrikkel
Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.Plan

Arkivstruktur.NasjonaleIdentifikatorer.Posisjon <-[hidden]-- Arkivstruktur.NasjonaleIdentifikatorer.Koordinatsystem
@enduml
