@startuml
class Sakarkiv.Avskrivning {
  +systemID : SystemID [0..1]
  +avskrivningsdato : datetime
  +avskrevetAv : string
  +referanseAvskrevetAv : SystemID [0..1]
  +avskrivningsmaate : Avskrivningsmaate
  +referanseAvskrivesAvJournalpost : SystemID [0..1]
  +referanseAvskrivesAvKorrespondansepart : SystemID [0..1]
}
@enduml
