@startuml
skinparam classAttributeIconSize 0
!include kapitler/media/uml-class-endringslogg.iuml
!include kapitler/media/uml-class-hendelseslogg.iuml
!include kapitler/media/uml-codelist-hendelsetype.iuml
LoggingOgSporing.Endringslogg <|-- LoggingOgSporing.Hendelseslogg
@enduml
