@startuml
class Admin.Bruker {
  +systemID : SystemID [0..1] [1..1]
  +brukerNavn : string
  +opprettetDato : datetime [0..1] [1..1]
  +opprettetAv : string [0..1] [1..1]
  +avsluttetDato : datetime [0..1]
  +virksomhetsspesifikkeMetadata : VirksomhetsspesifikkeMetadata [0..1]
  +kortnavn : string [0..1]
}
@enduml
