@startuml
class Arkivstruktur.NasjonaleIdentifikatorer.Matrikkel <Nasjonalidentifikator> {
  +kommunenummer : string
  +gaardsnummer : integer
  +bruksnummer : integer
  +festenummer : string [0..1]
  +seksjonsnummer : string [0..1]
}
@enduml
