@startuml
skinparam classAttributeIconSize 0
skinparam nodesep 180

!include kapitler/media/uml-class-journalpost-all.iuml
!include kapitler/media/uml-class-korrespondansepart.iuml
!include kapitler/media/uml-class-presedens.iuml
!include kapitler/media/uml-class-avskrivning.iuml
!include kapitler/media/uml-class-dokumentflyt.iuml
!include kapitler/media/uml-codelist-journalposttype.iuml
!include kapitler/media/uml-codelist-journalstatus.iuml
!include kapitler/media/uml-codelist-flytstatus.iuml

Kodelister.FlytStatus <-[hidden]-- Sakarkiv.Dokumentflyt
Sakarkiv.Dokumentflyt "+dokumentflyt 0..*" <--* Sakarkiv.Journalpost
Sakarkiv.Korrespondansepart "+korrespondansepart 0..*" <--* Sakarkiv.Journalpost
Sakarkiv.Presedens "+presedens 0..*" <--o "+journalpost 0..*" Sakarkiv.Journalpost
Sakarkiv.Journalpost *-> "+avskrivning 0..*" Sakarkiv.Avskrivning
Sakarkiv.Journalpost <-[hidden]-- Kodelister.Journalposttype
Sakarkiv.Journalpost <-[hidden]-- Kodelister.Journalstatus
@enduml
