@startuml
skinparam nodesep 100
hide circle
class MoeteOgUtvalgsbehandling.Moetemappe <Mappe> {
  +moetenummer : integer
  +utvalg : string
  +moetedeltaker : Moetedeltaker [1..*]
  +moetedato : date
  +moetested : string [0..1]
}
class Arkivstruktur.Mappe <Arkivenhet> {
}
Arkivstruktur.Mappe <|-- MoeteOgUtvalgsbehandling.Moetemappe
MoeteOgUtvalgsbehandling.Moetemappe "nestemoetemappe 0..1" o--> "forrigemoetemappe 0..1" MoeteOgUtvalgsbehandling.Moetemappe
class MoeteOgUtvalgsbehandling.Moetedeltaker <<dataType>> {
}
MoeteOgUtvalgsbehandling.Moetemappe *-- "moetedeltaker 1..*" MoeteOgUtvalgsbehandling.Moetedeltaker
MoeteOgUtvalgsbehandling.Moetemappe *-- MoeteOgUtvalgsbehandling.Moetedeltaker
@enduml
