@startuml
class Arkivstruktur.PartPerson <Part> {
  +personidentifikator : Personidentifikator [0..*]
  +navn : string
  +postadresse : EnkelAdresse [0..1]
  +bostedsadresse : EnkelAdresse [0..1]
  +kontaktinformasjon : Kontaktinformasjon [0..1]
}
@enduml
