@startuml
skinparam classAttributeIconSize 0

class Arkivstruktur.Klasse <Arkivenhet>
class Arkivstruktur.Arkivdel <Arkivenhet>
!include kapitler/media/uml-class-saksmappe.iuml
!include kapitler/media/uml-class-mappe-all.iuml
class Sakarkiv.Presedens
class Arkivstruktur.Registrering <Arkivenhet>
class MoeteOgUtvalgsbehandling.Moetemappe {
  +moetenummer : string [0..1]
  +utvalg : string
  +moetedato : datetime
  +moetested : string [0..1]
  +referanseForrigeMoete : SystemID [0..1]
  +referanseNesteMoete : SystemID [0..1]
}

Arkivstruktur.Arkivdel "+arkivdel 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Klasse --o "+underklasse 0..*" Arkivstruktur.Klasse
Arkivstruktur.Klasse "+klasse 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Arkivstruktur.Arkivdel "+arkivdel 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Klasse "+klasse 0..1" o--> "+mappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Klasse "+sekundaerklassifikasjon 0..*" <--o Sakarkiv.Saksmappe
Arkivstruktur.Mappe o--> "+undermappe 0..*" Arkivstruktur.Mappe
Arkivstruktur.Mappe "+mappe 0..1" o--> "+registrering 0..*" Arkivstruktur.Registrering
Sakarkiv.Saksmappe "+sak 0..*" o--> "+presedens 0..*" Sakarkiv.Presedens
Arkivstruktur.Mappe <|-- Sakarkiv.Saksmappe
Arkivstruktur.Mappe <|-- MoeteOgUtvalgsbehandling.Moetemappe

@enduml
