@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.NasjonaleIdentifikatorer.Posisjon <Nasjonalidentifikator> {
  +koordinatsystem : Koordinatsystem
  +x : decimal
  +y : decimal
  +z : decimal [0..1]
}
class Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator {
}
Arkivstruktur.NasjonaleIdentifikatorer.Nasjonalidentifikator <|-- Arkivstruktur.NasjonaleIdentifikatorer.Posisjon
@enduml
