@startuml
class Arkivstruktur.NasjonaleIdentifikatorer.Matrikkel <Nasjonalidentifikator> {
  +kommunenummer : string
  +gaardsnummer : integer
  +bruksnummer : integer
  +festenummer : integer [0..1]
  +seksjonsnummer : integer [0..1]
}
@enduml
