@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.UtfoertKassasjon <<dataType>> {
  +kassertDato : datetime [0..1] [1..1]
  +kassertAv : string [0..1] [1..1]
  +referanseKassertAv : SystemID [0..1] [1..1]
}
class Arkivstruktur.Arkivdel <Arkivenhet> {
}
Arkivstruktur.Arkivdel *-- Arkivstruktur.UtfoertKassasjon
class Arkivstruktur.Dokumentbeskrivelse <Arkivenhet> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.UtfoertKassasjon
@enduml
