@startuml
skinparam nodesep 100
hide circle
class Arkivstruktur.Dokumentbeskrivelse <Arkivenhet> {
  +dokumenttype : Dokumenttype [0..1] [1..1]
  +dokumentstatus : Dokumentstatus [0..1] [1..1]
  +tittel : string
  +beskrivelse : string [0..1]
  +forfatter : string [0..*]
  +dokumentmedium : Dokumentmedium [0..1] [1..1]
  +oppbevaringssted : string [0..1]
  +tilknyttetRegistreringSom : TilknyttetRegistreringSom [0..1] [1..1]
  +dokumentnummer : integer [0..1] [1..1]
  +tilknyttetDato : datetime [0..1] [1..1]
  +tilknyttetAv : string [0..1] [1..1]
  +referanseTilknyttetAv : SystemID [0..1] [1..1]
  +kassasjon : Kassasjon [0..1]
  +utfoertKassasjon : UtfoertKassasjon [0..1]
  +sletting : Sletting [0..1]
  +skjerming : Skjerming [0..1]
  +gradering : Gradering [0..1]
  +elektroniskSignatur : ElektroniskSignatur [0..1]
  +eksternReferanse : string [0..1]
  +virksomhetsspesifikkeMetadata : VirksomhetsspesifikkeMetadata [0..1]
}
class Arkivstruktur.Arkivenhet {
}
Arkivstruktur.Arkivenhet <|-- Arkivstruktur.Dokumentbeskrivelse
class Arkivstruktur.Dokumentobjekt <Arkivenhet> {
}
Arkivstruktur.Dokumentbeskrivelse "dokumentbeskrivelse 1" o--> "dokumentobjekt 0..*" Arkivstruktur.Dokumentobjekt
class Arkivstruktur.Merknad {
}
Arkivstruktur.Dokumentbeskrivelse *-- "merknad 0..*" Arkivstruktur.Merknad
class Arkivstruktur.Part {
}
Arkivstruktur.Dokumentbeskrivelse *-- "part 0..*" Arkivstruktur.Part
class Arkivstruktur.ElektroniskSignatur <<dataType>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.ElektroniskSignatur
class Arkivstruktur.Gradering <<dataType>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.Gradering
class Arkivstruktur.Kassasjon <<dataType>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.Kassasjon
class Arkivstruktur.Skjerming <<dataType>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.Skjerming
class Arkivstruktur.Sletting <<dataType>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.Sletting
class Arkivstruktur.UtfoertKassasjon <<dataType>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- Arkivstruktur.UtfoertKassasjon
class VirksomhetsspesifikkeMetadata.VirksomhetsspesifikkeMetadata <<VirksomhetsspesifikkeMetadata>> {
}
Arkivstruktur.Dokumentbeskrivelse *-- VirksomhetsspesifikkeMetadata.VirksomhetsspesifikkeMetadata
class Arkivstruktur.Registrering <Arkivenhet> {
}
Arkivstruktur.Registrering "registrering 1..*" o--> "dokumentbeskrivelse 0..*" Arkivstruktur.Dokumentbeskrivelse
@enduml
